### ISSUE TITLE
questions about train 

### ISSUE THREAD

**Issue by Veyronl** [datquocnguyen/jointRE#1]
Thanks for your hard word,
1.I have learned the paper,found that 
'although using Biaffine increases training time over using Linear by 35%, relatively,',I want to know the speed of train and the machine configuration
2.whether to support batch_size?
I want to use it in my Chinese dataset

Looking forward to your reply

**Comment by Veyronl** [comment]
3. the principle of Biaffine?

**Comment by datquocnguyen** [comment]
Hi,
1. it took several hours on CPU to train the model. 
2. My code is implemented without mini-batches.
