### ISSUE TITLE
How do you load the saved model ?

### ISSUE THREAD

**Issue by sr33kant** [datquocnguyen/jointRE#4]
Im working on something similar so curios how you load a saved model to be used as inference.I understand we'd have to load the parameters file from what I have seen params file is not getting created.

**Comment by datquocnguyen** [comment]
The current uploaded code automatically evaluates the performance on the dev set, after each training epoch, without saving the learned parameters. 

To save the model parameters:

- First, you add the following two code lines **before code [line 79](https://github.com/datquocnguyen/jointRE/blob/45c0a88f668fdc636417c3ff11aaaccba50c1a3a/jNERE/jNERE.py#L79)**:

    `with open("PATH-TO-VOCAB-FILE", 'w') as paramsfp:`
    &nbsp;&nbsp;&nbsp;&nbsp;`pickle.dump((words, nertags, rels, w2i, c2i, options), paramsfp)`

    Then you uncomment the code [line 112](https://github.com/datquocnguyen/jointRE/blob/45c0a88f668fdc636417c3ff11aaaccba50c1a3a/jNERE/jNERE.py#L112) to save learned parameters: 

    `parser.Save("PATH-TO-LEARNED-MODEL-FILE")` 

- Then for loading a trained model, you can use:

    `words, nertags, rels, w2i, c2i, options =  pickle.load("PATH-TO-VOCAB-FILE")`
    `trained_model = learner.jNeRE(words, nertags, rels, w2i, c2i, options)`
    `trained_model.Load("PATH-TO-LEARNED-MODEL-FILE")`
    `predTest, relsTest = trained_model.Predict(test_data)`

**Comment by sr33kant** [comment]
thank you , I was able to figure out. Sorry I didn't close the bug. I have another question. Any reason you aren't using POS tags but  just the count of posTag? I have created a separate project with some code from this project to generate ternary relationships.  Would you be interested in  collaborating on a shortest path dependency feature to this model  if you have the badnwidth
